### ISSUE TITLE
Fishing with Create mod doesn't drop any items from this mod

### ISSUE THREAD

**Issue by Amzd** [timinc-cobble/cobblemon-unimplementeditems#33]
Fishing with Create mod doesn't drop any items from this mod.

I created an auto fishing setup that gets treasure items but not Unimplemented Items drops 

![image](https://github.com/timinc-cobble/cobblemon-unimplementeditems/assets/17001151/8d74d6d9-b78b-4e3c-843f-329ce3567afd)

**Comment by Amzd** [comment]
Actually, after 4 hours I just got the first bottlecap. It just takes a while

**Comment by tmetcalfe89** [comment]
Yep. Working on a better distribution method. Currently a *tiny* chance on the fishing treasure table. Tho, tbf, I've had people manually fish a couple up. RNG is like that.
