### ISSUE TITLE
Ability Capsule not changing hidden ability

### ISSUE THREAD

**Issue by FullMetalMaster** [timinc-cobble/cobblemon-unimplementeditems#40]
currently you can't change the Pokemon ability back from hidden ability, if a Pokemon already has a hidden ability you can no longer change it back to its normal abilities I don't know if this is a bug or not

**Comment by tmetcalfe89** [comment]
That is the function of an [Ability Capsule](<https://bulbapedia.bulbagarden.net/wiki/Ability_Capsule>).
> It also cannot be used to change a Pokémon to or from its species' [Hidden Ability](https://bulbapedia.bulbagarden.net/wiki/Hidden_Ability).
